/** Semantic color tokens — keep in sync with globals.css */
export const colors = {
  bgDarkest: 'var(--color-bg-darkest)',
  bgDark: 'var(--color-bg-dark)',
  bgPanel: 'var(--color-bg-panel)',
  bgElevated: 'var(--color-bg-elevated)',
  textPrimary: 'var(--color-text-primary)',
  textSecondary: 'var(--color-text-secondary)',
  textTertiary: 'var(--color-text-tertiary)',
  borderSubtle: 'var(--color-border-subtle)',
  borderActive: 'var(--color-border-active)',
  borderFaint: 'var(--color-border-faint)',
  statusVital: 'var(--color-status-vital)',
  statusWarning: 'var(--color-status-warning)',
  statusAlert: 'var(--color-status-alert)',
  accentClarity: 'var(--color-accent-clarity)',
  accentInsight: 'var(--color-accent-insight)',
  accentInsightSubtle: 'var(--color-accent-insight-subtle)',
  accentInsightBorder: 'var(--color-accent-insight-border)',
  accentClaritySubtle: 'var(--color-accent-clarity-subtle)',
  accentClarityMuted: 'var(--color-accent-clarity-muted)',
  accentClarityBorder: 'var(--color-accent-clarity-border)',
  statusVitalBg: 'var(--color-status-vital-bg)',
  statusWarningBg: 'var(--color-status-warning-bg)',
  statusAlertBg: 'var(--color-status-alert-bg)',
  statusAlertBorder: 'var(--color-status-alert-border)',
  statusAlertBgStrong: 'var(--color-status-alert-bg-strong)',
  surfaceHover: 'var(--color-surface-hover)',
  overlay: 'var(--color-overlay)',
} as const
